# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vale < Formula
  desc "Simplified Technical English linter and stdio MCP server."
  homepage "https://github.com/stuffbucket/vale"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stuffbucket/vale/releases/download/v0.1.0/vale_0.1.0_darwin_amd64.tar.gz"
      sha256 "3b66c5387af793eb83d263282abaf1bafc8e2364b2762d0780f3bea39ac3d6a9"

      define_method(:install) do
        bin.install "vale"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stuffbucket/vale/releases/download/v0.1.0/vale_0.1.0_darwin_arm64.tar.gz"
      sha256 "54dc5692dea411f19be38bebee3d32e2a8b26d6d74bc9cbb176369b9be00a771"

      define_method(:install) do
        bin.install "vale"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stuffbucket/vale/releases/download/v0.1.0/vale_0.1.0_linux_amd64.tar.gz"
      sha256 "960f50ad58256cfa139ccc8b3f6b1719f41eb29ce4c0770281322f4f5224fe44"
      define_method(:install) do
        bin.install "vale"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stuffbucket/vale/releases/download/v0.1.0/vale_0.1.0_linux_arm64.tar.gz"
      sha256 "c45fa6d967e355d929d8f3a6a733cd232b853d58a68807383fa05e4a837b0e30"
      define_method(:install) do
        bin.install "vale"
      end
    end
  end

  test do
    system "#{bin}/vale", "version"
  end
end
