# typed: strict
# frozen_string_literal: true

# This formula was auto-generated by scripts/generate-formula.sh
class Bladerunner < Formula
  desc "Standalone Incus VM runner for macOS using Apple Virtualization.framework"
  homepage "https://github.com/stuffbucket/bladerunner"
  version "0.1.0"
  license "MIT"

  url "https://github.com/stuffbucket/bladerunner/releases/download/v0.1.0/bladerunner_0.1.0_darwin_aarch64.tar.gz"
  sha256 "4b59d2f9163f1b1e5e8791faace4679ab36530c823adee69d4c2bc3b50d6a59e"

  depends_on :macos
  depends_on macos: :ventura
  depends_on arch: :arm64

  def install
    bin.install "br"
    # Install entitlements file to share directory for reference
    share.install "vz.entitlements"
  end

  def post_install
    # Codesign the binary with Virtualization entitlements after installation
    # Requires Xcode Command Line Tools (codesign utility)
    unless system "which", "codesign", [:out, :err] => File::NULL
      opoo "codesign not found - Xcode Command Line Tools may not be installed"
      opoo "Install with: xcode-select --install"
      opoo "Then re-sign the binary: codesign --entitlements \#{share}/vz.entitlements -s - \#{bin}/br"
      return
    end

    # Sign the binary with Virtualization framework entitlements
    system "codesign", "--entitlements", "\#{share}/vz.entitlements", "-s", "-", "-f", "\#{bin}/br"
    
    # Verify the signature was applied
    unless system "codesign", "--verify", "\#{bin}/br", [:out, :err] => File::NULL
      opoo "Failed to verify codesign - the binary may not work correctly"
      opoo "You can manually re-sign with: codesign --entitlements \#{share}/vz.entitlements -s - \#{bin}/br"
    end
  end

  def caveats
    <<~EOS
      bladerunner uses Apple's Virtualization framework.

      Requirements:
      - Apple Silicon Mac (M1/M2/M3/M4)
      - macOS 13+ (Ventura or later)
      - Xcode Command Line Tools (for codesigning)

      Intel Macs are not supported.

      If you don't have Xcode Command Line Tools installed:
        xcode-select --install

      The binary is automatically signed with Virtualization entitlements during
      installation. If you encounter permission issues, manually re-sign:
        codesign --entitlements \#{share}/vz.entitlements -s - \#{bin}/br

      For bridged networking, additional entitlements may be needed.
      See: https://github.com/stuffbucket/bladerunner#bridged-networking
    EOS
  end

  test do
    assert_match version.to_s, shell_output("\#{bin}/br --version 2>&1")
  end
end
