# typed: strict
# frozen_string_literal: true

# This formula was auto-generated by scripts/generate-formula.sh
class Coop < Formula
  desc "AI agent container management with security sandboxing"
  homepage "https://github.com/stuffbucket/coop"
  version "0.1.3"
  license "MIT"

  depends_on "colima"

  on_macos do
    on_arm do
      url "https://github.com/stuffbucket/coop/releases/download/v0.1.3/coop_0.1.3_darwin_aarch64.tar.gz"
      sha256 "b2462ba0ffd2fe076380c60ce473650cf3a409a94f00c31a9cc7b6e7f2a04760"
    end
    on_intel do
      url "https://github.com/stuffbucket/coop/releases/download/v0.1.3/coop_0.1.3_darwin_x86_64.tar.gz"
      sha256 "d0dc473b1fa5491efb34b81db2f4b0937dda6119cca1a36756d87044950fcbba"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuffbucket/coop/releases/download/v0.1.3/coop_0.1.3_linux_aarch64.tar.gz"
      sha256 "1e424cd2042bba6847a720e921d661067d0d497f2f5d012c46c9319c4c2b90da"
    end
    on_intel do
      url "https://github.com/stuffbucket/coop/releases/download/v0.1.3/coop_0.1.3_linux_x86_64.tar.gz"
      sha256 "fef03327fa6d53207bead0d0a3173a030accb4ba06304adb2cdf86e0164f2131"
    end
  end

  def install
    bin.install "coop"
  end

  def caveats
    <<~EOS
      coop requires colima < 0.7.0. If you have a newer version installed,
      you may need to downgrade:
        brew install colima@0.6
    EOS
  end

  test do
    # Verify colima version is compatible
    colima_version = shell_output("#{Formula["colima"].opt_bin}/colima version 2>&1")[/colima version ([\d.]+)/, 1]
    if colima_version
      assert Gem::Version.new(colima_version) < Gem::Version.new("0.7.0"),
             "coop requires colima < 0.7.0, but #{colima_version} is installed"
    end
    assert_match version.to_s, shell_output("#{bin}/coop --version")
  end
end
