# typed: strict
# frozen_string_literal: true

# This formula was auto-generated by scripts/generate-formula.sh
class Coop < Formula
  desc "AI agent container management with security sandboxing"
  homepage "https://github.com/stuffbucket/coop"
  version "0.1.2"
  license "MIT"

  depends_on "colima" => "< 0.7.0"

  on_macos do
    on_arm do
      url "https://github.com/stuffbucket/coop/releases/download/v0.1.2/coop_0.1.2_darwin_aarch64.tar.gz"
      sha256 "ff8acc63975c7c00d1dcb4387435bd3fadd8336acb7baea81e78afe2e2962a85"
    end
    on_intel do
      url "https://github.com/stuffbucket/coop/releases/download/v0.1.2/coop_0.1.2_darwin_x86_64.tar.gz"
      sha256 "9ce9baccdc8d58be08f579df6f0a3feba00fcdbe0e97754011e125453de4bde1"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/stuffbucket/coop/releases/download/v0.1.2/coop_0.1.2_linux_aarch64.tar.gz"
      sha256 "f55140c123f08cfb0b609f0f2ce01a9339d903fe4383cb0e362463371e3a8d1e"
    end
    on_intel do
      url "https://github.com/stuffbucket/coop/releases/download/v0.1.2/coop_0.1.2_linux_x86_64.tar.gz"
      sha256 "beb91b44d14367a8b45c739fe6c1ef36a8ee46148f9ba72ef7e1139835d7fdc0"
    end
  end

  def install
    bin.install "coop"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/coop --version")
  end
end
