# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loopd < Formula
  desc "Export Loop pages to portable Markdown with images preserved"
  homepage "https://github.com/stuffbucket/loopd"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stuffbucket/loopd/releases/download/v0.1.1/loopd_0.1.1_darwin_x86_64.tar.gz"
      sha256 "32be3f35a8bef005d7d691d355a18bc7806d78ff0de7465b11309601ca20c2ec"

      def install
        bin.install "loopd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stuffbucket/loopd/releases/download/v0.1.1/loopd_0.1.1_darwin_aarch64.tar.gz"
      sha256 "e2d54104d4a6467bb8ded98a6caaec613ff9baff397285bd89458a3dc3e95be1"

      def install
        bin.install "loopd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stuffbucket/loopd/releases/download/v0.1.1/loopd_0.1.1_linux_x86_64.tar.gz"
      sha256 "5b99373b0032fb91d468ed1b6782d4b52253130adff5f4ebb5f0c6cb126eec41"
      def install
        bin.install "loopd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stuffbucket/loopd/releases/download/v0.1.1/loopd_0.1.1_linux_aarch64.tar.gz"
      sha256 "1f6d872e327c4b5d2b9c62bcaccb460ceffa25473125b58c825925bc6c7b3198"
      def install
        bin.install "loopd"
      end
    end
  end

  test do
    system bin/"loopd", "--version"
  end
end
