# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loopd < Formula
  desc "Export Loop pages to portable Markdown with images preserved"
  homepage "https://github.com/stuffbucket/loopd"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stuffbucket/loopd/releases/download/v0.1.0/loopd_0.1.0_darwin_amd64.tar.gz"
      sha256 "bd607954a0f7cd53303c582756a140aeb70773a72131d5c75aac48276bf2bf04"

      def install
        bin.install "loopd"
        # Install plugin files for --copy-script and --export-plugin
        (share/"loopd/plugins/loopd-loop-export").install "plugins/loopd-loop-export/loopd.js"
        (share/"loopd/plugins/loopd-markdown-importer").install Dir["plugins/loopd-markdown-importer/*"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stuffbucket/loopd/releases/download/v0.1.0/loopd_0.1.0_darwin_arm64.tar.gz"
      sha256 "b8641f557bce57a94e02b853f657c000885d0326deef50441dfdf9412501d9fc"

      def install
        bin.install "loopd"
        # Install plugin files for --copy-script and --export-plugin
        (share/"loopd/plugins/loopd-loop-export").install "plugins/loopd-loop-export/loopd.js"
        (share/"loopd/plugins/loopd-markdown-importer").install Dir["plugins/loopd-markdown-importer/*"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stuffbucket/loopd/releases/download/v0.1.0/loopd_0.1.0_linux_amd64.tar.gz"
      sha256 "8607872c589d7b502481bc902931675262f97d19ce6f50986bcbf5e7ea829183"
      def install
        bin.install "loopd"
        # Install plugin files for --copy-script and --export-plugin
        (share/"loopd/plugins/loopd-loop-export").install "plugins/loopd-loop-export/loopd.js"
        (share/"loopd/plugins/loopd-markdown-importer").install Dir["plugins/loopd-markdown-importer/*"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stuffbucket/loopd/releases/download/v0.1.0/loopd_0.1.0_linux_arm64.tar.gz"
      sha256 "3577325ef0968b3da09838f3d2b34e7abc07cad2692ff8416727da6a5b9dd73f"
      def install
        bin.install "loopd"
        # Install plugin files for --copy-script and --export-plugin
        (share/"loopd/plugins/loopd-loop-export").install "plugins/loopd-loop-export/loopd.js"
        (share/"loopd/plugins/loopd-markdown-importer").install Dir["plugins/loopd-markdown-importer/*"]
      end
    end
  end

  test do
    system "#{bin}/loopd", "--version"
  end
end
