# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vale < Formula
  desc "Simplified Technical English linter and stdio MCP server."
  homepage "https://github.com/stuffbucket/vale"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stuffbucket/vale/releases/download/v0.6.0/vale_0.6.0_darwin_amd64.tar.gz"
      sha256 "9b2508428896bfeab10989fe2ed5bcb903456bd2066dc734cb02b43559932560"

      define_method(:install) do
        bin.install "vale"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stuffbucket/vale/releases/download/v0.6.0/vale_0.6.0_darwin_arm64.tar.gz"
      sha256 "323bde1c4673f9352d678b5d41e97c2af93d35c4bcd1521b65d3ad2c046362f9"

      define_method(:install) do
        bin.install "vale"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stuffbucket/vale/releases/download/v0.6.0/vale_0.6.0_linux_amd64.tar.gz"
      sha256 "640b2e0f5cc07d509ba3789a8caa57125b58b18f19edabae8a34649c279d11f7"
      define_method(:install) do
        bin.install "vale"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stuffbucket/vale/releases/download/v0.6.0/vale_0.6.0_linux_arm64.tar.gz"
      sha256 "70b760661226858403ab4b707f0b3c0fd0e5eb89a351fe1da496713fa10d0777"
      define_method(:install) do
        bin.install "vale"
      end
    end
  end

  test do
    system "#{bin}/vale", "version"
  end
end
